name: mindfeed
description: "AI-summarized news tailored to user interests."
publish_to: 'none' # Remove this line if you intend to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0' # Adjusted for modern Dart

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^2.27.2
  firebase_auth: ^4.18.0
  cloud_firestore: ^4.15.10
  google_sign_in: ^6.2.1
  flutter_appauth: ^7.0.0
  google_sign_in: ^6.2.1
  # UI & Utilities
  flutter_spinkit: ^5.2.1
  image_picker: ^1.0.7 # Check for latest
  image_cropper: ^5.0.1 # Check for latest
  dio: ^5.4.1 # Check for latest (for Cloudinary upload)
  cached_network_image: ^3.3.1 # For displaying network images efficiently

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/google_logo.png