// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA46CHIK69TfjbkPqBqMa3s8GDBdC1yQDg',
    appId: '1:800725396436:web:539b14aaa5311c11e48441',
    messagingSenderId: '800725396436',
    projectId: 'mindfeed-139b1',
    authDomain: 'mindfeed-139b1.firebaseapp.com',
    storageBucket: 'mindfeed-139b1.firebasestorage.app',
    measurementId: 'G-ZSR9FVVHQT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNMZsGmMBHpwGA15l5AfI7C07yzgc3oxA',
    appId: '1:800725396436:android:1a57fa524a8cfc1be48441',
    messagingSenderId: '800725396436',
    projectId: 'mindfeed-139b1',
    storageBucket: 'mindfeed-139b1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABlCwq7w94INMFySt7Hbbx5Sxm7smnAQk',
    appId: '1:800725396436:ios:4b4c74648345992fe48441',
    messagingSenderId: '800725396436',
    projectId: 'mindfeed-139b1',
    storageBucket: 'mindfeed-139b1.firebasestorage.app',
    iosBundleId: 'com.example.mindfeed',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABlCwq7w94INMFySt7Hbbx5Sxm7smnAQk',
    appId: '1:800725396436:ios:4b4c74648345992fe48441',
    messagingSenderId: '800725396436',
    projectId: 'mindfeed-139b1',
    storageBucket: 'mindfeed-139b1.firebasestorage.app',
    iosBundleId: 'com.example.mindfeed',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA46CHIK69TfjbkPqBqMa3s8GDBdC1yQDg',
    appId: '1:800725396436:web:20a6736e1b6fa954e48441',
    messagingSenderId: '800725396436',
    projectId: 'mindfeed-139b1',
    authDomain: 'mindfeed-139b1.firebaseapp.com',
    storageBucket: 'mindfeed-139b1.firebasestorage.app',
    measurementId: 'G-VYR71ZHK9J',
  );
}
